type User {
    _id: String
    name: String
    email: String
    token: String
    createdAt: String
    updatedAt: String
}

input UserInput {
    name: String!
    email: String!
    password: String!
}

input UserUpdateInput {
    password: String
}

type Query {
    signIn(email: String, password: String): User!
}

type Mutation {
    createUser(userInput: UserInput): User!
    updateUser(ID: ID!, userInput: UserUpdateInput): Boolean
}
