type Task {
    _id: String
    name: String
    description: String
    status: Boolean
    createdAt: String
    updatedAt: String
}

input TaskInput {
    name: String
    description: String
    status: Boolean
}

type Query {
    findTask(ID: ID!): Task!
    allTasks: [Task]
}

type Mutation {
    createTask(taskInput: TaskInput): Task!
    updateTask(ID: ID!, taskInput: TaskInput): Boolean
    deleteTask(ID: ID!): Boolean
}
